name: tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Show local directory
        run: ls -la
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.7.1"

      - name: Install dependencies
        run: poetry install
      
      - name: Run pytest
        run: poetry run python -m pytest --log-cli-level=DEBUG --save-energy-report --energy-offset-zero

      - name: Save energy report
        uses: actions/upload-artifact@v4
        with:
          name: energy-report
          path: reports/energy/
